import { QueryProviders } from "@/components/providers/query-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App - StackKit",
  description: "Generated by create next app with StackKit template",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn(geistMono.variable, "font-sans", geist.variable)}>
      <head />
      <body className="font-sans antialiased" suppressHydrationWarning>
<ThemeProvider
  attribute="class"
  defaultTheme="system"
  enableSystem
  disableTransitionOnChange
>
        
<TooltipProvider>
<QueryProviders>{children}</QueryProviders>
</TooltipProvider>
        <Toaster theme="system" position="top-right" richColors />
      
</ThemeProvider>
</body>
    </html>
  );
}
